version: '3'
services:
  client:
    stdin_open: true
    tty: true
    build: ./client
    ports: 
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
  server:
    build: ./server
    ports: 
      - "1010:1010"
    volumes:
      - ./server:/app/src
    env_file:
      - ./server/.env

